### ISSUE TITLE
Scrollable Tooltip

### ISSUE THREAD

**Issue by NhunorGaming** [LifeIsAParadox/Skyblocker#43]
Add ability to Scroll through tooltip like the mod "Tooltip Scroll"

**Comment by TacoMonkey11** [comment]
tooltip scrolling isn't really a feature that should be in a skyblock utility mod, it would be better to keep it as a separate mod so that others can enjoy it without needed to install this mod

though I have found this [fork](https://github.com/turtletowerz/Tooltip-Scroll-Fabric/tree/1.18) of tooltip scroll which seems to be updated to 1.18 (Haven't tested it though)

**Comment by NhunorGaming** [comment]
Thank you very much
